// Generated by `vails dts` from the capability grants in vails.json - do not edit.
// Services: clipboard 0.1.0, opener 0.1.0, notification 0.1.0, os_info 0.1.0
// App: Vails Services Demo 0.1.0
export namespace clipboard {
	export const service: string;
	export const version: string;
	export function read_text(params: undefined): Promise<string>;
	export function write_text(params: string): Promise<string>;
}
export namespace opener {
	export interface OpenerUrlOptions { url: string; }
	export interface OpenerPathOptions { path: string; with?: string; }
	export const service: string;
	export const version: string;
	export function open_url(params: OpenerUrlOptions): Promise<string>;
	export function open_path(params: OpenerPathOptions): Promise<string>;
}
export namespace notification {
	export interface NotificationOptions { title?: string; body: string; timeout_ms?: number; }
	export const service: string;
	export const version: string;
	export function notify(params: NotificationOptions): Promise<string>;
	export function is_supported(params: undefined): Promise<boolean>;
}
export namespace os_info {
	export interface OsInfo {
		os: string;
		arch: string;
		hostname: string;
		cwd: string;
		home_dir: string;
		temp_dir: string;
		exe_path: string;
		cpus: number;
	}
	export const service: string;
	export const version: string;
	export function get(params: undefined): Promise<OsInfo>;
}
