// Generated by `vails dts` from the capability grants in vails.json - do not edit.
// Services: clipboard 0.1.0, opener 0.1.0, notification 0.1.0, balloon 0.1.0, menu 0.1.0, dialog 0.1.0, tray 0.1.0, os_info 0.1.0
// App: Vails Services Demo 0.1.0
export namespace clipboard {
	export const service: string;
	export const version: string;
	export function read_text(params: undefined): Promise<string>;
	export function write_text(params: string): Promise<string>;
}
export namespace opener {
	export interface OpenerUrlOptions { url: string; }
	export interface OpenerPathOptions { path: string; with?: string; }
	export const service: string;
	export const version: string;
	export function open_url(params: OpenerUrlOptions): Promise<string>;
	export function open_path(params: OpenerPathOptions): Promise<string>;
}
export namespace notification {
	export interface NotificationOptions { title?: string; body: string; timeout_ms?: number; actions?: NotificationAction[]; }
	export interface NotificationAction { id: string; content: string; arguments?: string; placement?: "contextual" | "system"; }
	export const service: string;
	export const version: string;
	export function notify(params: NotificationOptions): Promise<string>;
	export function is_supported(params: undefined): Promise<boolean>;
}
export namespace balloon {
	export interface BalloonOptions { title?: string; body: string; timeout_ms?: number; }
	export const service: string;
	export const version: string;
	export function show(params: BalloonOptions): Promise<string>;
	export function is_supported(params: undefined): Promise<boolean>;
}
export namespace menu {
	export interface MenuItem { id?: string; label?: string; enabled?: boolean; separator?: boolean; children?: MenuItem[]; }
	export interface MenuPopup { items: MenuItem[]; }
	export interface MenuClicked { id: string; }
	export interface MenuCanceled { canceled: true; }
	export const service: string;
	export const version: string;
	/** popup blocks the UI until it is answered (a native modal). Do not call it from a loop or a startup path; it is the documented exception to the "handlers must be fast" threading rule (ADR-0014). */
	export function popup(params: MenuPopup): Promise<string>;
	export function close(params: undefined): Promise<string>;
	export function set_menu(params: MenuPopup): Promise<string>;
}
export namespace dialog {
	export interface DialogFilter { name: string; extensions: string; }
	export interface DialogOpenOptions { title?: string; default_path?: string; filters?: DialogFilter[]; multi?: boolean; folder?: boolean; }
	export interface DialogSaveOptions { title?: string; default_path?: string; default_name?: string; filters?: DialogFilter[]; }
	export interface DialogMessageOptions { title?: string; message: string; buttons?: 'ok' | 'okcancel' | 'yesnocancel'; }
	export interface DialogFileResult { canceled: boolean; paths: string[]; button: string; }
	export interface DialogMessageResult { canceled: boolean; paths: string[]; button: string; }
	export const service: string;
	export const version: string;
	/** open blocks the UI until it is answered (a native modal). Do not call it from a loop or a startup path; it is the documented exception to the "handlers must be fast" threading rule (ADR-0014). */
	export function open(params: DialogOpenOptions): Promise<DialogFileResult>;
	/** save blocks the UI until it is answered (a native modal). Do not call it from a loop or a startup path; it is the documented exception to the "handlers must be fast" threading rule (ADR-0014). */
	export function save(params: DialogSaveOptions): Promise<DialogFileResult>;
	/** message blocks the UI until it is answered (a native modal). Do not call it from a loop or a startup path; it is the documented exception to the "handlers must be fast" threading rule (ADR-0014). */
	export function message(params: DialogMessageOptions): Promise<DialogMessageResult>;
}
export namespace tray {
	export interface TrayOptions { icon?: string; tooltip?: string; }
	export interface TrayClick { button: "left" | "right"; }
	export const service: string;
	export const version: string;
	export function set(params: TrayOptions): Promise<string>;
	export function destroy(params: undefined): Promise<string>;
	export function set_menu(params: MenuPopup): Promise<string>;
}
export namespace os_info {
	export interface OsInfo {
		os: string;
		arch: string;
		hostname: string;
		cwd: string;
		home_dir: string;
		temp_dir: string;
		exe_path: string;
		cpus: number;
	}
	export const service: string;
	export const version: string;
	export function get(params: undefined): Promise<OsInfo>;
}
