// Generated by `vails dts` from the capability grants in vails.json - do not edit.
// Services: dialog 0.1.0, os_info 0.1.0
// App: Vails Dialog Demo 0.1.0
export namespace dialog {
	export interface DialogFilter { name: string; extensions: string; }
	export interface DialogOpenOptions { title?: string; defaultPath?: string; filters?: DialogFilter[]; multi?: boolean; }
	export interface DialogSaveOptions { title?: string; defaultPath?: string; defaultName?: string; filters?: DialogFilter[]; }
	export interface DialogMessageOptions { title?: string; message: string; buttons?: 'ok' | 'okcancel' | 'yesnocancel'; }
	export interface DialogFileResult { canceled: boolean; paths: string[]; button: string; }
	export interface DialogMessageResult { canceled: boolean; paths: string[]; button: string; }
	export const service: string;
	export const version: string;
	export function open(params: DialogOpenOptions): Promise<DialogFileResult>;
	export function save(params: DialogSaveOptions): Promise<DialogFileResult>;
	export function message(params: DialogMessageOptions): Promise<DialogMessageResult>;
}
export namespace os_info {
	export interface OsInfo {
		os: string;
		arch: string;
		hostname: string;
		cwd: string;
		home_dir: string;
		temp_dir: string;
		exe_path: string;
		cpus: number;
	}
	export const service: string;
	export const version: string;
	export function get(params: undefined): Promise<OsInfo>;
}
